services:

  postgres:
    image: postgres:16
    container_name: learnova-db
    environment:
      POSTGRES_USER: learnova
      POSTGRES_PASSWORD: password
      POSTGRES_DB: learnova
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: