import { Injectable, Inject, Logger, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { GenerateQuizDto, QuizDifficultyLevel } from './dto/generate-quiz.dto';

export interface GeneratedQuestionOption {
  text: string;
  isCorrect: boolean;
  explanation: string;
}

export interface GeneratedQuestion {
  text: string;
  difficulty: QuizDifficultyLevel;
  conceptTested: string;
  options: GeneratedQuestionOption[];
}

export interface GeneratedQuizResponse {
  quizTitle: string;
  courseTitle: string;
  sessionTitle?: string;
  difficulty: QuizDifficultyLevel;
  questionCount: number;
  passingScore: number;
  savedQuizId?: number;
  questions: GeneratedQuestion[];
}

interface ConceptTopic {
  title: string;
  category: string;
  details?: string;
}

@Injectable()
export class QuizGeneratorService {
  private readonly logger = new Logger(QuizGeneratorService.name);

  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}

  async generateQuiz(dto: GenerateQuizDto): Promise<GeneratedQuizResponse> {
    const course = await this.prisma.client.course.findUnique({
      where: { id: dto.courseId },
      include: {
        sessions: {
          include: {
            videos: { select: { id: true, title: true, content: true, description: true } },
            quizzes: {
              include: {
                questions: {
                  include: {
                    options: true,
                  },
                },
              },
            },
          },
          orderBy: { orderNumber: 'asc' },
        },
        quizzes: {
          include: {
            questions: {
              include: {
                options: true,
              },
            },
          },
        },
      },
    });

    if (!course) {
      throw new NotFoundException(`Course with ID ${dto.courseId} not found.`);
    }

    let targetSessionTitle: string | undefined;
    let targetSession: (typeof course.sessions)[0] | undefined;

    if (dto.sessionId) {
      targetSession = course.sessions.find(s => s.id === dto.sessionId);
      if (!targetSession) {
        throw new NotFoundException(`Session with ID ${dto.sessionId} not found in this course.`);
      }
      targetSessionTitle = targetSession.title;
    }

    const difficulty = dto.difficulty || QuizDifficultyLevel.BEGINNER;
    const count = Math.min(20, Math.max(1, dto.questionCount || 5));

    const quizTitle = dto.title || (targetSessionTitle
      ? `AI Assessment: ${targetSessionTitle} (${difficulty})`
      : `General AI Assessment: ${course.title} (${difficulty})`);

    // Case 1: Saving pre-generated validated questions directly
    if (dto.saveToDatabase && dto.questions && Array.isArray(dto.questions) && dto.questions.length > 0) {
      const createdQuiz = await this.prisma.client.quiz.create({
        data: {
          title: quizTitle,
          description: `Quiz generated and validated via Learnova AI for ${difficulty} level. Passing threshold: 70%.`,
          courseId: course.id,
          sessionId: dto.sessionId || null,
          passingScore: 70,
          timeLimitMinutes: Math.max(5, dto.questions.length * 2),
          isExamMode: false,
          allowReviewAfterSubmission: true,
          randomizeAnswers: true,
          randomizeQuestions: true,
          showExplanationAfterAnswer: true,
          questions: {
            create: dto.questions.map((q: any) => ({
              text: q.text,
              options: {
                create: (q.options || []).map((opt: any) => ({
                  text: typeof opt === 'object' ? (opt.text || '') : String(opt || ''),
                  isCorrect: typeof opt === 'object' ? Boolean(opt.isCorrect) : false,
                  explanation: typeof opt === 'object' ? (opt.explanation || null) : null,
                })),
              },
            })),
          },
        },
      });

      return {
        quizTitle,
        courseTitle: course.title,
        sessionTitle: targetSessionTitle,
        difficulty,
        questionCount: dto.questions.length,
        passingScore: 70,
        savedQuizId: createdQuiz.id,
        questions: dto.questions,
      };
    }

    // Case 2: Generate brand new, non-redundant, diverse questions
    const generatedQuestions = this.extractAndGenerateQuestions(
      course,
      targetSession,
      difficulty,
      count,
    );

    let savedQuizId: number | undefined;

    // Persist to PostgreSQL if save was requested without explicit questions array
    if (dto.saveToDatabase) {
      const createdQuiz = await this.prisma.client.quiz.create({
        data: {
          title: quizTitle,
          description: `Quiz automatically generated by Learnova AI from course study materials for ${difficulty} level. Passing threshold: 70%.`,
          courseId: course.id,
          sessionId: dto.sessionId || null,
          passingScore: 70,
          timeLimitMinutes: Math.max(5, count * 2),
          isExamMode: false,
          allowReviewAfterSubmission: true,
          randomizeAnswers: true,
          randomizeQuestions: true,
          showExplanationAfterAnswer: true,
          questions: {
            create: generatedQuestions.map(q => ({
              text: q.text,
              options: {
                create: q.options.map(opt => ({
                  text: opt.text,
                  isCorrect: opt.isCorrect,
                  explanation: opt.explanation,
                })),
              },
            })),
          },
        },
      });
      savedQuizId = createdQuiz.id;
    }

    return {
      quizTitle,
      courseTitle: course.title,
      sessionTitle: targetSessionTitle,
      difficulty,
      questionCount: generatedQuestions.length,
      passingScore: 70,
      savedQuizId,
      questions: generatedQuestions,
    };
  }

  private extractAndGenerateQuestions(
    course: any,
    targetSession: any | undefined,
    difficulty: QuizDifficultyLevel,
    count: number,
  ): GeneratedQuestion[] {
    const contextName = targetSession ? targetSession.title : course.title;
    const questions: GeneratedQuestion[] = [];
    const seenPrompts = new Set<string>();

    const normalize = (str: string) => str.trim().toLowerCase().replace(/[^\w\s]/g, '');

    // 1. Gather all existing high-quality questions from the course/session in database
    const existingDbQuestions: GeneratedQuestion[] = [];
    const candidateQuizzes = targetSession
      ? (targetSession.quizzes || [])
      : [
          ...(course.quizzes || []),
          ...course.sessions.flatMap((s: any) => s.quizzes || []),
        ];

    for (const qz of candidateQuizzes) {
      for (const q of qz.questions || []) {
        if (q.options && q.options.length >= 4 && q.options.some((o: any) => o.isCorrect)) {
          const correctOpt = q.options.find((o: any) => o.isCorrect);
          const distractors = q.options.filter((o: any) => !o.isCorrect);
          if (correctOpt && distractors.length >= 3) {
            existingDbQuestions.push({
              text: q.text,
              difficulty,
              conceptTested: targetSession?.title || course.title,
              options: this.shuffleArray([
                {
                  text: correctOpt.text,
                  isCorrect: true,
                  explanation: correctOpt.explanation || `Correct answer according to course standards for ${course.title}.`,
                },
                ...distractors.slice(0, 3).map((d: any) => ({
                  text: d.text,
                  isCorrect: false,
                  explanation: d.explanation || `Incorrect option according to pedagogical guidelines.`,
                })),
              ]),
            });
          }
        }
      }
    }

    // 2. Extract rich topics and concepts from sessions, videos, and lecture notes
    const topics: ConceptTopic[] = [];
    const relevantSessions = targetSession ? [targetSession] : course.sessions;

    for (const session of relevantSessions) {
      const cleanSessionTitle = this.cleanTitle(session.title);
      if (cleanSessionTitle.length > 3) {
        topics.push({
          title: cleanSessionTitle,
          category: 'Session',
          details: session.description || undefined,
        });
      }

      for (const video of session.videos || []) {
        const cleanVideoTitle = this.cleanTitle(video.title);
        if (cleanVideoTitle.length > 3 && cleanVideoTitle !== cleanSessionTitle) {
          topics.push({
            title: cleanVideoTitle,
            category: 'Lesson',
            details: video.description || undefined,
          });
        }

        // Extract markdown headers and key points from video content
        if (video.content) {
          const lines = video.content.split('\n');
          for (const line of lines) {
            const trimmed = line.trim();
            if (trimmed.startsWith('#') || trimmed.startsWith('##') || trimmed.startsWith('###')) {
              const headerText = trimmed.replace(/^#+\s*/, '').trim();
              if (headerText.length > 5 && headerText.length < 80) {
                topics.push({
                  title: headerText,
                  category: 'Key Section',
                });
              }
            } else if (trimmed.includes(':') && (trimmed.startsWith('-') || trimmed.startsWith('*'))) {
              const [key, val] = trimmed.replace(/^[-*]\s*/, '').split(':');
              if (key && val && key.trim().length > 4 && key.trim().length < 60) {
                topics.push({
                  title: key.trim().replace(/\*\*/g, ''),
                  category: 'Core Concept',
                  details: val.trim().replace(/\*\*/g, ''),
                });
              }
            }
          }
        }
      }
    }

    // Fallback topics if course notes are minimal
    if (topics.length === 0) {
      topics.push(
        { title: `${course.title} - Architecture & Foundations`, category: 'Architecture' },
        { title: `${course.title} - Data Flow & Transformation`, category: 'Processing' },
        { title: `${course.title} - Modeling & Domain Rules`, category: 'Modeling' },
        { title: `${course.title} - Performance Optimization`, category: 'Optimization' },
        { title: `${course.title} - Security & Governance`, category: 'Security' },
        { title: `${course.title} - Integration & Best Practices`, category: 'Best Practices' },
      );
    }

    // Shuffle both pools to ensure different questions on every regeneration
    const shuffledDbQuestions = this.shuffleArray(existingDbQuestions);
    const shuffledTopics = this.shuffleArray(topics);

    // If we have DB questions, we can draw a balanced portion from them
    const maxDbQuestions = Math.min(Math.floor(count / 2), shuffledDbQuestions.length);
    for (let i = 0; i < maxDbQuestions; i++) {
      const candidate = shuffledDbQuestions[i];
      const norm = normalize(candidate.text);
      if (!seenPrompts.has(norm)) {
        seenPrompts.add(norm);
        questions.push(candidate);
      }
    }

    // Procedurally synthesize distinct questions across the unique topics
    let topicIndex = 0;
    let attemptCount = 0;
    const maxAttempts = count * 6;

    while (questions.length < count && attemptCount < maxAttempts) {
      attemptCount++;
      const currentTopic = shuffledTopics[topicIndex % shuffledTopics.length];
      topicIndex++;

      const questionArchetype = (questions.length + attemptCount) % 6;
      let generated: GeneratedQuestion;

      if (difficulty === QuizDifficultyLevel.BEGINNER) {
        generated = this.generateBeginnerArchetype(contextName, currentTopic, questionArchetype);
      } else if (difficulty === QuizDifficultyLevel.INTERMEDIATE) {
        generated = this.generateIntermediateArchetype(contextName, currentTopic, questionArchetype);
      } else {
        generated = this.generateAdvancedArchetype(contextName, currentTopic, questionArchetype);
      }

      const norm = normalize(generated.text);
      if (!seenPrompts.has(norm)) {
        seenPrompts.add(norm);
        questions.push(generated);
      }
    }

    return questions.slice(0, count);
  }

  // --- BEGINNER QUESTION ARCHETYPES (Foundational Knowledge & Definitions) ---
  private generateBeginnerArchetype(
    context: string,
    topic: ConceptTopic,
    archetype: number,
  ): GeneratedQuestion {
    const name = topic.title;
    let prompt = '';
    let correctText = '';
    let correctExp = '';
    let distractor1 = '';
    let exp1 = '';
    let distractor2 = '';
    let exp2 = '';
    let distractor3 = '';
    let exp3 = '';

    switch (archetype % 6) {
      case 0:
        prompt = `Regarding "${context}", what is the fundamental objective targeted by "${name}"?`;
        correctText = topic.details
          ? `Understand and master the core principles: ${topic.details.substring(0, 110)}.`
          : `Acquire methodological and conceptual mastery of "${name}" to build solid foundations.`;
        correctExp = `Correct. Mastering "${name}" establishes an essential foundation for learning.`;
        distractor1 = `Deliberately ignore prerequisites to speed up execution without structure.`;
        exp1 = `Incorrect. Rigorous learning requires progressive assimilation of foundational prerequisites.`;
        distractor2 = `Replace all analytical modules with an intuitive approach without validation.`;
        exp2 = `Incorrect. A structured methodology is required to ensure consistency.`;
        distractor3 = `Limit learning to rote memorization of terms without understanding mechanisms.`;
        exp3 = `Incorrect. Competence relies on understanding practical concepts rather than mere memorization.`;
        break;

      case 1:
        prompt = `In the curriculum for "${context}", which statement most accurately characterizes "${name}"?`;
        correctText = `A core structural component that helps organize and clarify the workflow.`;
        correctExp = `Correct. "${name}" plays an essential framing role in this learning path.`;
        distractor1 = `An obsolete procedure maintained solely for archiving with no practical use.`;
        exp1 = `Incorrect. This module is an integral part of the modern curriculum.`;
        distractor2 = `An optional third-party tool with no relation to certification assessments.`;
        exp2 = `Incorrect. Associated skills are directly evaluated for certification.`;
        distractor3 = `A secondary mechanism automatically replacing human decision-making without configuration.`;
        exp3 = `Incorrect. Mastering fundamentals requires conscious and structured configuration.`;
        break;

      case 2:
        prompt = `What initial step is essential when getting started with "${name}"?`;
        correctText = `Identify key components and configure the environment according to course recommendations.`;
        correctExp = `Excellent answer. Environment setup is the prerequisite for any successful implementation.`;
        distractor1 = `Launch execution immediately without verifying sources or initialization parameters.`;
        exp1 = `Hazardous. This systematically leads to configuration and runtime errors.`;
        distractor2 = `Disable all security and integrity checks to simplify testing.`;
        exp2 = `Critical error. Integrity protocols must remain active.`;
        distractor3 = `Delete required dependencies to artificially minimize project size.`;
        exp3 = `Incorrect. Removing required dependencies breaks system functionality.`;
        break;

      case 3:
        prompt = `Why is it crucial for a learner to validate their knowledge of "${name}"?`;
        correctText = `Because these foundational concepts condition success in advanced sessions and certification exams.`;
        correctExp = `Completely accurate. Assimilation of these concepts determines future proficiency.`;
        distractor1 = `Because this module is entirely detached from the rest of the course.`;
        exp1 = `Incorrect. The Learnova curriculum is progressive and interconnected.`;
        distractor2 = `To automatically obtain a perfect score without completing the other requirements.`;
        exp2 = `Incorrect. Certification requires completing the full curriculum with at least 70% score.`;
        distractor3 = `To eliminate the need to ever consult technical documentation.`;
        exp3 = `Incorrect. Consulting documentation remains an essential continuous practice.`;
        break;

      case 4:
        prompt = `Among the following options, what is the golden rule established in "${name}"?`;
        correctText = `Adopt a methodical approach, document decisions, and follow established conventions.`;
        correctExp = `Well done. Thorough documentation and convention compliance ensure high quality.`;
        distractor1 = `Avoid any standardization to maintain complete freedom without guidelines.`;
        exp1 = `Incorrect. Industry standards ensure readability and interoperability.`;
        distractor2 = `Rely entirely on chance without systematic review protocols.`;
        exp2 = `Unacceptable. Quality depends on systematic verification.`;
        distractor3 = `Modify critical parameters in live production without saving stable checkpoints.`;
        exp3 = `Incorrect. Traceability and version control are essential.`;
        break;

      default:
        prompt = `Within the scope of "${context}", what is the primary purpose addressed in "${name}"?`;
        correctText = `Structure core knowledge to solve concrete challenges and advance with confidence.`;
        correctExp = `Correct. This section consolidates the learner's practical application skills.`;
        distractor1 = `Unnecessarily complicate the learning process with purely abstract exercises.`;
        exp1 = `Incorrect. Learnova's pedagogical approach is career and industry oriented.`;
        distractor2 = `Isolate the student from the learning platform without review opportunities.`;
        exp2 = `Incorrect. Pedagogical reviews and guidance are part of the core experience.`;
        distractor3 = `Prohibit modern tooling to enforce slow, outdated manual methods.`;
        exp3 = `Incorrect. The course teaches modern tools and up-to-date industry standards.`;
        break;
    }

    return {
      text: prompt,
      difficulty: QuizDifficultyLevel.BEGINNER,
      conceptTested: name,
      options: this.shuffleArray([
        { text: correctText, isCorrect: true, explanation: correctExp },
        { text: distractor1, isCorrect: false, explanation: exp1 },
        { text: distractor2, isCorrect: false, explanation: exp2 },
        { text: distractor3, isCorrect: false, explanation: exp3 },
      ]),
    };
  }

  // --- INTERMEDIATE QUESTION ARCHETYPES (Application, Method & Trade-offs) ---
  private generateIntermediateArchetype(
    context: string,
    topic: ConceptTopic,
    archetype: number,
  ): GeneratedQuestion {
    const name = topic.title;
    let prompt = '';
    let correctText = '';
    let correctExp = '';
    let distractor1 = '';
    let exp1 = '';
    let distractor2 = '';
    let exp2 = '';
    let distractor3 = '';
    let exp3 = '';

    switch (archetype % 6) {
      case 0:
        prompt = `In the technical application of "${context}", what methodological approach ensures optimal effectiveness of "${name}"?`;
        correctText = `Rigorously balance modularity and performance by applying clean decoupling principles.`;
        correctExp = `Correct. Component decoupling guarantees long-term reusability and maintainability.`;
        distractor1 = `Merge all data and business logic into a single monolithic block.`;
        exp1 = `Architectural anti-pattern. Excessive centralization generates major technical debt.`;
        distractor2 = `Ignore response times assuming underlying infrastructure will always compensate.`;
        exp2 = `Incorrect. Algorithmic and structural optimization must be designed from the start.`;
        distractor3 = `Multiply circular dependencies across modules to force synchronization.`;
        exp3 = `Incorrect. Circular dependencies cause deadlocks and unpredictable behavior.`;
        break;

      case 1:
        prompt = `When encountering an anomaly or inconsistent result in "${name}", what diagnostic strategy is recommended?`;
        correctText = `Isolate inputs, verify intermediate transformations, and validate schema consistency step by step.`;
        correctExp = `Excellent method. Component isolation accurately identifies the root cause.`;
        distractor1 = `Reset the entire environment without inspecting logs or stack traces.`;
        exp1 = `Inappropriate. This destroys vital evidence needed to understand the issue.`;
        distractor2 = `Manually hardcode outputs to mask the anomaly without fixing the root cause.`;
        exp2 = `Dangerous. Masking an anomaly destabilizes downstream consumers.`;
        distractor3 = `Disable all monitoring alerts and quality gates to suppress warnings.`;
        exp3 = `Unacceptable. Continuous alerts are essential to prevent future regressions.`;
        break;

      case 2:
        prompt = `What technical trade-off must be evaluated when configuring "${name}"?`;
        correctText = `The ratio between resource consumption (memory/compute) and required user responsiveness.`;
        correctExp = `Correct. Proper sizing balances computational footprint with latency and throughput.`;
        distractor1 = `Choosing between regulatory compliance or disabling all security for 1% speed gain.`;
        exp1 = `Unacceptable. Compliance and security are non-negotiable requirements.`;
        distractor2 = `Replacing automated unit tests with theoretical assumptions to save time.`;
        exp2 = `Incorrect. Test coverage is indispensable for operational robustness.`;
        distractor3 = `Maximizing code obscurity to discourage modifications by peers.`;
        exp3 = `Anti-pattern. Simplicity and clarity are hallmarks of professional engineering.`;
        break;

      case 3:
        prompt = `How should data flows be managed in "${name}" to prevent system bottlenecks?`;
        correctText = `Implement asynchronous pipelines or batching with proactive backpressure control.`;
        correctExp = `Spot on. Managing ingestion rates prevents queue exhaustion and memory spikes.`;
        distractor1 = `Execute continuous synchronous blocking calls directly against primary production databases.`;
        exp1 = `Bad practice. This introduces severe locking and performance degradation.`;
        distractor2 = `Disable caching to force repeated re-computation of every incoming payload.`;
        exp2 = `Inefficient. Strategic caching is necessary to relieve compute bottlenecks.`;
        distractor3 = `Persist all volatile transaction data in unindexed temporary flat files.`;
        exp3 = `Inappropriate. Structured, indexed storage is required for predictable access times.`;
        break;

      case 4:
        prompt = `Which validation best practice guarantees the ongoing reliability of outputs produced by "${name}"?`;
        correctText = `Define automated regression test suites and compare outputs against certified benchmark baselines.`;
        correctExp = `Very good. Automated regression testing preserves system stability across iterations.`;
        distractor1 = `Rely exclusively on the lack of immediate complaints from end users.`;
        exp1 = `Insufficient. Proactive validation prevents silent data corruption.`;
        distractor2 = `Dynamically alter acceptance criteria so the test suite always scores 100%.`;
        exp2 = `Invalid. Acceptance criteria must be documented, strict, and immutable.`;
        distractor3 = `Purge all version logs to keep only the latest unversioned run.`;
        exp3 = `Incorrect. Auditing requires complete, traceable version history.`;
        break;

      default:
        prompt = `In the continuous optimization of "${context}", which initiative enhances the value of "${name}"?`;
        correctText = `Automate recurring workflows, standardize naming conventions, and monitor efficiency metrics.`;
        correctExp = `Correct. Process industrialization delivers consistency, quality, and significant time savings.`;
        distractor1 = `Introduce ad-hoc manual interventions during every deployment cycle.`;
        exp1 = `Inappropriate. Repetitive manual actions are a primary vector for human errors.`;
        distractor2 = `Employ proprietary closed formats to prevent third-party interoperability.`;
        exp2 = `Error. Interoperability and open standards are crucial for long-term scalability.`;
        distractor3 = `Delegate governance to unauthorized external entities without service level agreements (SLAs).`;
        exp3 = `Incorrect. Technical governance must remain managed and bound by clear SLAs.`;
        break;
    }

    return {
      text: prompt,
      difficulty: QuizDifficultyLevel.INTERMEDIATE,
      conceptTested: name,
      options: this.shuffleArray([
        { text: correctText, isCorrect: true, explanation: correctExp },
        { text: distractor1, isCorrect: false, explanation: exp1 },
        { text: distractor2, isCorrect: false, explanation: exp2 },
        { text: distractor3, isCorrect: false, explanation: exp3 },
      ]),
    };
  }

  // --- ADVANCED QUESTION ARCHETYPES (Enterprise Governance, Resilience & Edge Cases) ---
  private generateAdvancedArchetype(
    context: string,
    topic: ConceptTopic,
    archetype: number,
  ): GeneratedQuestion {
    const name = topic.title;
    let prompt = '';
    let correctText = '';
    let correctExp = '';
    let distractor1 = '';
    let exp1 = '';
    let distractor2 = '';
    let exp2 = '';
    let distractor3 = '';
    let exp3 = '';

    switch (archetype % 6) {
      case 0:
        prompt = `When deploying "${context}" standards in enterprise environments, which governance practice ensures highest resilience against edge cases in "${name}"?`;
        correctText = `Apply Security by Design, maintain an immutable audit trail, and periodically review performance metrics.`;
        correctExp = `Excellent answer. Enterprise governance relies on auditability, native security, and continuous improvement.`;
        distractor1 = `Disable event logging during peak traffic periods to save storage space.`;
        exp1 = `Unacceptable in production. Compliance and auditability require complete traceability.`;
        distractor2 = `Trust all incoming internal payloads without validation once inside the network perimeter.`;
        exp2 = `Dangerous. The Zero Trust architecture mandates strict verification of every inbound request.`;
        distractor3 = `Freeze all system development permanently once initial compliance is met.`;
        exp3 = `Inappropriate. Modern architectures require ongoing reviews to adapt to emerging threats.`;
        break;

      case 1:
        prompt = `In high-availability architectures handling "${name}", how can cascading failures during degraded service be prevented?`;
        correctText = `Implement circuit breakers, load shedding mechanisms, and graceful degradation fallback policies.`;
        correctExp = `Well done. Circuit breakers isolate localized failures and prevent systemic collapse.`;
        distractor1 = `Indefinitely increase timeouts and retry counts without exponential backoff.`;
        exp1 = `Critical mistake. This amplifies congestion and triggers the thundering herd problem.`;
        distractor2 = `Destroy and recreate the entire cluster in production upon detecting any minor error.`;
        exp2 = `Catastrophic. This causes widespread outages for all active users.`;
        distractor3 = `Route all failed transactions to an unbounded, unmonitored in-memory queue.`;
        exp3 = `Inappropriate. Unbounded in-memory queues inevitably cause out-of-memory (OOM) crashes.`;
        break;

      case 2:
        prompt = `Regarding advanced security and data transit compliance in "${name}", which protocol is imperative in enterprise environments?`;
        correctText = `End-to-end encryption (at-rest & in-transit), mutual TLS (mTLS), and fine-grained role-based access control (RBAC/ABAC).`;
        correctExp = `Perfect. Defense-in-depth protects critical assets even if an individual component is breached.`;
        distractor1 = `Share a single root administrator account with static, never-rotated API tokens.`;
        exp1 = `Major security violation. Accountability requires short-lived, individual credentials.`;
        distractor2 = `Disable internal encryption under the assumption that the physical datacenter is secure.`;
        exp2 = `Violates Zero Trust standards. Multi-layer defense mandates encryption across all channels.`;
        distractor3 = `Grant public unauthenticated read access to internal database schemas to simplify integration.`;
        exp3 = `Dangerous. Unrestricted metadata exposure facilitates adversary reconnaissance.`;
        break;

      case 3:
        prompt = `When processing massive heterogeneous data volumes in "${name}", which modeling strategy delivers predictable query performance?`;
        correctText = `Thoughtfully partition entities, precompute key aggregations, and maintain selective indexes aligned with query workloads.`;
        correctExp = `Excellent. Partitioning and targeted indexing prevent expensive full table scans.`;
        distractor1 = `Execute full Cartesian joins across tables without temporal or dimensional filtering predicates.`;
        exp1 = `Disastrous for performance. This produces combinatorial explosion in query output.`;
        distractor2 = `Prohibit partitioning to force all records into a single monolithic, unsegmented table.`;
        exp2 = `Unsuitable for enterprise scale. Monolithic tables rapidly bottleneck horizontal scaling.`;
        distractor3 = `Perform global in-memory sorting on unindexed free-text fields under high concurrency.`;
        exp3 = `Unviable under load. Sorting arbitrary text columns without indexes consumes excessive memory.`;
        break;

      case 4:
        prompt = `Which critical architectural anti-pattern must be strictly avoided when designing deep integrations for "${name}"?`;
        correctText = `Shared Database Anti-Pattern (tight coupling via common database) without documented, versioned API contracts.`;
        correctExp = `Correct. Direct shared databases break deployment independence and entangle schema evolution.`;
        distractor1 = `Adopting strict API contracts with semantic payload validation.`;
        exp1 = `Incorrect. Strict contracts are an industry best practice promoting decoupled stability.`;
        distractor2 = `Establishing systematic peer code reviews and continuous integration test pipelines.`;
        exp2 = `Incorrect. Continuous integration is a foundational pillar of modern software engineering.`;
        distractor3 = `Monitoring 99th percentile latency (p99) telemetry across distributed services.`;
        exp3 = `Incorrect. Tracking p99 latency is crucial for diagnosing tail degradations.`;
        break;

      default:
        prompt = `In the context of auditability and regulatory compliance for "${name}", which requirement is strictly non-negotiable?`;
        correctText = `Maintain an immutable state change audit trail with cryptographic timestamps and supervised access governance.`;
        correctExp = `Very good. Cryptographic integrity and tamper-proof logs are fundamental for regulatory verification.`;
        distractor1 = `Allow manual rewriting of audit logs to adjust historic discrepancies.`;
        exp1 = `Illegal in regulated audits. Audit logs must never be retroactively altered.`;
        distractor2 = `Purge all operational logs after 24 hours to evade accountability in legal disputes.`;
        exp2 = `Non-compliant. Frameworks like GDPR, ISO 27001, and SOX mandate strict retention periods.`;
        distractor3 = `Log sensitive credentials and plaintext authentication secrets into standard debug logs.`;
        exp3 = `Severe vulnerability. Credentials must never be transmitted or stored in application log output.`;
        break;
    }

    return {
      text: prompt,
      difficulty: QuizDifficultyLevel.ADVANCED,
      conceptTested: name,
      options: this.shuffleArray([
        { text: correctText, isCorrect: true, explanation: correctExp },
        { text: distractor1, isCorrect: false, explanation: exp1 },
        { text: distractor2, isCorrect: false, explanation: exp2 },
        { text: distractor3, isCorrect: false, explanation: exp3 },
      ]),
    };
  }

  private cleanTitle(title: string): string {
    return (title || '')
      .replace(/^Session\s+\d+:\s*/i, '')
      .replace(/^Leçon\s+\d+:\s*/i, '')
      .replace(/^Vidéo\s+\d+:\s*/i, '')
      .replace(/^Chapitre\s+\d+:\s*/i, '')
      .replace(/^Module\s+\d+:\s*/i, '')
      .replace(/^Introduction to\s+/i, '')
      .replace(/^Introduction à\s+/i, '')
      .trim();
  }

  private shuffleArray<T>(array: T[]): T[] {
    const arr = [...array];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }
}
